name: Aliyun Signin


on：
  schedule：
   # 每天国际时间17:20 运行一次，中国时间01:20
    - cron:'2017***
   workflow dispatch:
jobs:
si gnin:
name: Aliyun Signin 
runs-on: ubuntu- latest
steps:
uses: ImYr5/aliyun-auto-si gningnain
with :
REFRESH TOKENS: ${{ secrets .REFRESH TOKENS }}
GP TOKEN: ${{ secrets .GP TOKEN}}
PUSH TYPES: 'TEL EGRAM
TELEGRAM BOT_ TOKEN: ${{ secrets.TELEGRAM BOT TOKEN }}
TELEGRAM CHAT ID: ${{ secrets.TELEGRAM _CHAT_ID }}
